codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/*.spec.*"
  - "**/test/**"
  - "src/main.tsx"
  - "src/Main.jsx"
  - "vite.config.ts"
  - "vitest.config.ts"
  - "playwright.config.ts"
  - "eslint.config.js"
